### ISSUE TITLE
数据库连接出错？这是什么问题

### ISSUE THREAD

**Issue by liupengfei1010** [thx/rap2-delos#100]
Unable to connect to the database: { SequelizeConnectionError: connect ETIMEDOUT
    at Utils.Promise.tap.then.catch.err (/code/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
    at tryCatcher (/code/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/code/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/code/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/code/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/code/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/code/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/code/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/code/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)

**Comment by Bosn** [comment]
本区不负责mysql教学哦
