### ISSUE TITLE
create-db出错

### ISSUE THREAD

**Issue by feiyu0123** [thx/rap2-delos#130]
数据库已建好，但是执行npm run create-db报错
```
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
(node:6537) UnhandledPromiseRejectionWarning: TypeError: sequelize.drop is not a function
    at Object.<anonymous> (/home/ubuntu/rap2-delos/dist/scripts/init/delos.js:18:25)
    at Generator.next (<anonymous>)
    at /home/ubuntu/rap2-delos/dist/scripts/init/delos.js:6:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/rap2-delos/dist/scripts/init/delos.js:2:12)
    at Object.init (/home/ubuntu/rap2-delos/dist/scripts/init/delos.js:17:12)
    at /home/ubuntu/rap2-delos/dist/scripts/init/index.js:13:23
    at Generator.next (<anonymous>)
    at /home/ubuntu/rap2-delos/dist/scripts/init/index.js:6:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/rap2-delos/dist/scripts/init/index.js:2:12)
    at main (/home/ubuntu/rap2-delos/dist/scripts/init/index.js:12:12)
    at Object.<anonymous> (/home/ubuntu/rap2-delos/dist/scripts/init/index.js:20:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
(node:6537) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:6537) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
SQL 2018-04-16 03:20:56.065 SELECT 1+1 AS result
----------------------------------------
DATABASE √
    HOST     localhost
    PORT     3306
    DATABASE rap2_delos_app
----------------------------------------
```

**Comment by Bosn** [comment]
已修复，见上面的commit

是TS化后的import BUG导致的。
