### ISSUE TITLE
点击状态菜单，后端analytics.js的sequelize报错如下

### ISSUE THREAD

**Issue by coalchan** [thx/rap2-delos#133]
TypeError: sequelize.query is not a function
      at Object.<anonymous> (/home/chenzhipeng/.local/lib/rap2-delos/dist/routes/analytics.js:109:34)
      at Generator.next (<anonymous>)
      at /home/chenzhipeng/.local/lib/rap2-delos/dist/routes/analytics.js:6:71
      at new Promise (<anonymous>)
      at __awaiter (/home/chenzhipeng/.local/lib/rap2-delos/dist/routes/analytics.js:2:12)
      at router_1.default.get (/home/chenzhipeng/.local/lib/rap2-delos/dist/routes/analytics.js:88:73)
      at dispatch (/home/chenzhipeng/.local/lib/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/home/chenzhipeng/.local/lib/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at /home/chenzhipeng/.local/lib/rap2-delos/node_modules/koa-router/lib/router.js:346:16
      at dispatch (/home/chenzhipeng/.local/lib/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at /home/chenzhipeng/.local/lib/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
      at dispatch (/home/chenzhipeng/.local/lib/rap2-delos/node_modules/koa-router/lib/router.js:351:31)
      at dispatch (/home/chenzhipeng/.local/lib/rap2-delos/node_modules/koa-compose/index.js:42:32)
      at next (/home/chenzhipeng/.local/lib/rap2-delos/node_modules/koa-compose/index.js:43:18)
      at /home/chenzhipeng/.local/lib/rap2-delos/node_modules/koa-body/index.js:98:14
      at <anonymous>

**Comment by Bosn** [comment]
我也发现了排查中，感谢反馈

**Comment by Bosn** [comment]
已修复，谢谢
