### ISSUE TITLE
登录后，“仓库”栏目，选择“所有仓库”，服务端nodejs程序报错

### ISSUE THREAD

**Issue by wwb568109135** [thx/rap2-delos#143]
步骤：登录后，“仓库”栏目，选择“所有仓库”，服务端nodejs程序报错

mac 本地 brew 安装的mysql程序，版本为5.7.13，node：9.10.1    

<-- GET /repository/list?user=&organization=&name=&cursor=1&limit=100
Unhandled rejection SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 7
    at Query.formatError (/Users/jerry/demo/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/jerry/demo/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/Users/jerry/demo/rap2-delos/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/Users/jerry/demo/rap2-delos/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/Users/jerry/demo/rap2-delos/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/Users/jerry/demo/rap2-delos/node_modules/mysql2/lib/packet_parser.js:77:14)

**Comment by kkroy-zs** [comment]
由于向后端传递的organization为空，所以数据库查询时的sql语句的查询条件值也为空。
`      SELECT COUNT(id) AS num FROM (
        SELECT o.id, o.name
        FROM Organizations o
        WHERE visibility = ${1} OR creatorId = ${userId} OR ownerId = ${userId}
        UNION
        SELECT o.id, o.name
        FROM Organizations o
        JOIN organizations_members om ON o.id = om.organizationId
        WHERE om.userId = ${userId}
      ) as result
      WHERE id = ${organizationId}
`
中的WHERE id = ${organizationId}值未赋上，导致生成的SQL变为id = 。

**Comment by Bosn** [comment]
最新的版本已经修复了，麻烦再试一下。

确实加了organization权限的判断，但是没处理好organization为空的状态。
