### ISSUE TITLE
布署手册能写得详细些吗。现在布署有问题

### ISSUE THREAD

**Issue by jasonx4131** [thx/rap2-delos#15]
npm run create-db时报下面的错误。
请指教
` rap2-delos@1.0.0 create-db /usr/local/rap2
> node scripts/init

/usr/local/rap2/scripts/init/index.js:5
async function main () {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "create-db"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! rap2-delos@1.0.0 create-db: `node scripts/init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-delos@1.0.0 create-db script 'node scripts/init'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rap2-delos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rap2-delos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rap2-delos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/rap2/npm-debug.log
`

**Comment by jasonx4131** [comment]
yum安装的Nodejs是6版本。这个需要安装nodejs9,。重新安装nodejs就好了
