### ISSUE TITLE
TypeError: Cannot create property 'headers' on boolean 'false'

### ISSUE THREAD

**Issue by xiaoxing598** [thx/rap2-delos#156]
An error occurred while requesting `http://xxx/repository/get?id=16`

```
TypeError: Cannot create property 'headers' on boolean 'false'
      at next.catch.err (/opt/rap2-delos/node_modules/_kcors@2.2.1@kcors/index.js:91:21)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

Prompted code in error location
```
 89       }
 90       return next().catch(err => {
 91         err.headers = Object.assign({}, err.headers, headersSet);
 92         throw err;
 93       });
 94     } else {
```

**Comment by xiaoxing598** [comment]
May be due to incorrect routing address?
```
router.get('/app/get', async (ctx, next) => {
  let data: any = {}
  let query = ctx.query
  let hooks: any = {
    repository: Repository,
    module: Module,
    interface: Interface,
    property: Property,
  }
  for (let name in hooks) {
    if (!query[name]) continue
    data[name] = await hooks[name].findById(query[name])
  }
  ctx.body = {
    data: Object.assign({}, ctx.body && ctx.body.data, data),
  }

  return next()
})
```

**Comment by Bosn** [comment]
hao de, shou dao !

Qing wen nin shi yong de rap2.taobao.org hai shi nin zi ji bu shu de fu wu qi ne ?

**Comment by xiaoxing598** [comment]
Internally deployed services

**Comment by Bosn** [comment]
所有仓库都取不到么？还是特定的取不到呢？

如果是特定的仓库，这个仓库的文档里有没有比较特殊的预发规则或内容呢？

**Comment by danxiao5201** [comment]
How did you solve it? I met the same problem.

**Comment by xiaoxing598** [comment]
@danxiao5201 这个框架比较坑，我现在改用http://yapi.demo.qunar.com/。
