### ISSUE TITLE
npm run create-db时候报错

### ISSUE THREAD

**Issue by smalpple** [thx/rap2-delos#164]
具体报错信息如下
```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'create-db' ]
2 info using npm@6.0.0
3 info using node@v8.9.4
4 verbose run-script [ 'precreate-db', 'create-db', 'postcreate-db' ]
5 info lifecycle rap2-delos@1.0.0~precreate-db: rap2-delos@1.0.0
6 info lifecycle rap2-delos@1.0.0~create-db: rap2-delos@1.0.0
7 verbose lifecycle rap2-delos@1.0.0~create-db: unsafe-perm in lifecycle true
8 verbose lifecycle rap2-delos@1.0.0~create-db: PATH: /root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/www/api2/rap2-delos/node_modules/.bin:/root/.nvm/versions/node/v8.9.4/bin:/www/mysql/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/jdk1.7.0_21/bin:/root/bin:/usr/local/maven/bin
9 verbose lifecycle rap2-delos@1.0.0~create-db: CWD: /www/api2/rap2-delos
10 silly lifecycle rap2-delos@1.0.0~create-db: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=development node dist/scripts/init' ]
11 silly lifecycle rap2-delos@1.0.0~create-db: Returned: code: 1  signal: null
12 info lifecycle rap2-delos@1.0.0~create-db: Failed to exec create-db script
13 verbose stack Error: rap2-delos@1.0.0 create-db: `cross-env NODE_ENV=development node dist/scripts/init`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid rap2-delos@1.0.0
15 verbose cwd /www/api2/rap2-delos
16 verbose Linux 3.10.0-123.el7.x86_64
17 verbose argv "/root/.nvm/versions/node/v8.9.4/bin/node" "/root/.nvm/versions/node/v8.9.4/bin/npm" "run" "create-db"
18 verbose node v8.9.4
19 verbose npm  v6.0.0
20 error code ELIFECYCLE
21 error errno 1
22 error rap2-delos@1.0.0 create-db: `cross-env NODE_ENV=development node dist/scripts/init`
22 error Exit status 1
23 error Failed at the rap2-delos@1.0.0 create-db script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
不知道什么原因。。。

**Comment by hydyy** [comment]
遇到了一样的问题

**Comment by Bosn** [comment]
按照README上面的操作走了嘛？什么系统也说一下啊。看到好多帖子，都只提供很片面的信息，根本没有办法预测问题

**Comment by blackdog1987** [comment]
日志不全
按照下面的去排查一下：

- 检查db配置信息是否正确，用其他客户端连接一次，保证配置没问题
- 检查一下数据库中是否有成功创建表，如果表成功创建了，参考#167 检查一下三个表的ddl中，priority是int还是bigint，需要设置为bigint(20)，dev模式跑create-db的时候会生成mock数据，可能导致insert表报错。或者是，修改一下这几个文件：

- src/modules/bo/property.ts
- src/modules/bo/module.ts
- src/modules/bo/interface.ts

找到这个：
```javascript
@Column
priority: number
```

修改为：
```javascript
@Column(DataType.BIGINT(20))
priority: number
```
