### ISSUE TITLE
repository/get?id=15 500 (Internal Server Error)

### ISSUE THREAD

**Issue by xiaoxing598** [thx/rap2-delos#165]
在请求后端服务出错，repository/get这个路由好像请求不了。

```
GET http://api-rap2.example.com/repository/get?id=15 500 (Internal Server Error)
```

其他接口都请求正常，比如仓库列表、团队列表等

**Comment by xiaoxing598** [comment]
@Bosn 在 `routes/repository.js` 文件中注释设置缓存就可以了，所以是这个设置缓存的问题，具体你可以再帮忙排查一下。

```
router.get('/repository/get', async (ctx) => {
......
//await RedisService.setCache(CACHE_KEY.REPOSITORY_GET, JSON.stringify(repository), ctx.query.id)
......
```

**Comment by xiaoxing598** [comment]
在设置缓存时发生错误，从错误中打印调用栈信息，发现 `set` 函数传参错误。

```js
static setCache(key, val, entityId, expireTime) {
        const cacheKey = this.getCacheKey(key, entityId);
        return new Promise((resolve, reject) => {
            RedisService.client.set(cacheKey, val, 'EX', expireTime || 1 * 24 * 60 * 60, (err) => {
                console.log('xxxxx==' + err.stack);  
                if (err) {
                    return reject(false);
                }
                return resolve(true);
            });
        });
    }
```

```js
ReplyError: ERR wrong number of arguments for 'set' command
    at new Command (/opt/rap2-delos/node_modules/_redis@2.8.0@redis/lib/command.js:12:22)
    at RedisClient.set (/opt/rap2-delos/node_modules/_redis@2.8.0@redis/lib/commands.js:58:47)
    at Promise (/opt/rap2-delos/dist/service/redis.js:26:33)
    at new Promise (<anonymous>)
    at Function.setCache (/opt/rap2-delos/dist/service/redis.js:25:16)
    at Object.<anonymous> (/opt/rap2-delos/dist/routes/repository.js:185:31)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/rap2-delos/dist/routes/repository.js:3:58)
    at <anonymous>
```

**Comment by Bosn** [comment]
看起来像是版本问题，因为线上跑的就是最新版，而且又是TypeScript强类型，如果是参数错误编译都不会通过。

**Comment by xiaoxing598** [comment]
从master上拉取的代码，是依赖的库版本问题吗？建议你指定具体的版本

**Comment by Bosn** [comment]
你redis什么版本啊？不要用测试版，或奇怪的版本，用最新的正常版本就好了。

**Comment by Bosn** [comment]
看起来应该是本机redis版本不匹配的问题。

**Comment by Bosn** [comment]
我用的版本您可以参考下：

```
Redis server v=4.0.2 sha=00000000:0 malloc=libc bits=64 build=9362cee5c362ea40
```

**Comment by xiaoxing598** [comment]
升级了redis之后，问题已经解决。
```
# /opt/redis/src/redis-server -v
Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=374b9d2325dbcc1c
```
