### ISSUE TITLE
SyntaxError: Unexpected token ' in JSON at position 5656

### ISSUE THREAD

**Issue by xiaoxing598** [thx/rap2-delos#168]
从rap1=>rap2导入仓库时发生错误：

```
  xxx POST /repository/import 500 114ms -

  SyntaxError: Unexpected token ' in JSON at position 5656
      at JSON.parse (<anonymous>)
      at Function.<anonymous> (/opt/rap2-delos/dist/service/migrate.js:116:38)
      at Generator.next (<anonymous>)
      at fulfilled (/opt/rap2-delos/dist/service/migrate.js:3:58)
      at <anonymous>

```

**Comment by Bosn** [comment]
给个例子啊亲，应该是特殊字符转义导致的。
如果数据敏感，你可以邮件发我 bosn@outlook.com

**Comment by xiaoxing598** [comment]
已经发给你了

**Comment by Bosn** [comment]
已修复
https://github.com/thx/rap2-delos/commit/2cc3e9010211948c3bb64d3bab513ac3a8aa11c3

**Comment by xiaoxing598** [comment]
问题并没有解决，并引入的新的问题。

```
 xxx POST /repository/import 500 76ms -

  Error: Cannot find module 'notevil'
      at Function.Module._resolveFilename (module.js:547:15)
      at Function.Module._load (module.js:474:25)
      at Module.require (module.js:596:17)
      at require (internal/module.js:11:18)
      at Function.<anonymous> (/opt/rap2-delos/dist/service/migrate.js:117:30)
      at Generator.next (<anonymous>)
      at fulfilled (/opt/rap2-delos/dist/service/migrate.js:3:58)
      at <anonymous>

```
