### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by jasonx4131** [thx/rap2-delos#17]
[在上一个问题](https://github.com/thx/rap2-delos/issues/16)未解决的情况下，我直接执行了
npm run dev
但报如下错误：
Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1496:7)
    at Application.listen (/usr/local/rap2/node_modules/koa/lib/application.js:64:19)
    at start (/usr/local/rap2/scripts/dev.js:8:7)
    at Object.<anonymous> (/usr/local/rap2/scripts/dev.js:19:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
[nodemon] app crashed - waiting for file changes before starting...

看上去是和端口有关，但我在config.dev.js  config.local.js  config.prod.js 文件里的port都已经改成别的端口了。

**Comment by Bosn** [comment]
8080端口有别的服务占用了

**Comment by jasonx4131** [comment]
@Bosn 是被占用了。这个我明白。但8080已经让重要的系统使用了。不便更改。
所以我想改这个玩意儿使用的端口。请问如何操作

**Comment by Bosn** [comment]
开发模式修改config.dev.js
生产模式修改config.prod.js


dolores前端模块也是一样的。

**Comment by jasonx4131** [comment]
vim config.dev.js
![11111111](https://user-images.githubusercontent.com/11881255/33466577-ca1a8ca4-d689-11e7-846e-6c0aa40b98c4.png)
vim config.prod.js
![22222222222](https://user-images.githubusercontent.com/11881255/33466589-df76ff6a-d689-11e7-8487-92f2fb4d0374.png)
奇怪就在这儿，都改过了的。
执行npm run dev，依旧使用的是8080
![33333333333](https://user-images.githubusercontent.com/11881255/33466624-1e25d984-d68a-11e7-9e01-8a1a6c22ce32.png)

**Comment by jasonx4131** [comment]
@Bosn yes，我找到了。vim /usr/local/rap2/scripts/dev.js  是这个文件里有指定8080。改了就好了。

**Comment by Bosn** [comment]
抱歉，这个应该是BUG，我改一下，应该从config中去读取配置。

另外README我全部都更新了中文和更为详细的注释，有需要可以看一下。

**Comment by Bosn** [comment]
commit 8dcdfb03dc823423bb12ad1c2e1c607c3c2402ac

已在上面commit中修复了dev.js不记载/config/中配置文件的BUG。
