### ISSUE TITLE
仓库-所有仓库的异常报告

### ISSUE THREAD

**Issue by lanmingle** [thx/rap2-delos#170]
``` bash
Fri, 11 May 2018 07:18:49 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
Fri, 11 May 2018 07:18:49 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
[2018-05-11 07:18:49.249] master#218 worker#236 is now connected to null:8080.
[2018-05-11 07:18:49.299] master#218 worker#241 is now connected to null:8080.
Unhandled rejection SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 7
    at Query.formatError (/opt/app/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/opt/app/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/opt/app/rap2-delos/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/opt/app/rap2-delos/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/opt/app/rap2-delos/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/opt/app/rap2-delos/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/opt/app/rap2-delos/node_modules/mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

验证的提交 ID: c0859f73a45b42710f3fde92902b40b96c0d71aa
使用的数据库: mysql 5.7.21 , redis 3.2.10

调用的接口:

``` bash
http://host/repository/list?user=&organization=&name=&cursor=1&limit=100
```

**Comment by lanmingle** [comment]
close #143
