### ISSUE TITLE
新增模块或者接口时无法插入数据库

### ISSUE THREAD

**Issue by 307guojiawei** [thx/rap2-delos#172]
新增模块或者接口时,比如`./module/create`，会报500错误，查看日志，发现错误如下：
```
0|rap-serv |   xxx POST /module/create 500 5ms -
0|rap-serv |   SequelizeDatabaseError: Out of range value for column 'priority' at row 1
0|rap-serv |       at Query.formatError (/root/rap/rap2-delos/node_modules/_sequelize@4.37.7@sequelize/lib/dialects/mysql/query.js:247:16)
0|rap-serv |       at Query.handler [as onResult] (/root/rap/rap2-delos/node_modules/_sequelize@4.37.7@sequelize/lib/dialects/mysql/query.js:68:23)
0|rap-serv |       at Query.Command.execute (/root/rap/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/commands/command.js:30:12)
0|rap-serv |       at Connection.handlePacket (/root/rap/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:502:28)
0|rap-serv |       at PacketParser.onPacket (/root/rap/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:81:16)
0|rap-serv |       at PacketParser.executeStart (/root/rap/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/packet_parser.js:77:14)
0|rap-serv |       at Socket.<anonymous> (/root/rap/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:89:29)
0|rap-serv |       at emitOne (events.js:115:13)
0|rap-serv |       at Socket.emit (events.js:210:7)
0|rap-serv |       at addChunk (_stream_readable.js:252:12)
0|rap-serv |       at readableAddChunk (_stream_readable.js:239:11)
0|rap-serv |       at Socket.Readable.push (_stream_readable.js:197:10)
0|rap-serv |       at TCP.onread (net.js:589:20)

```

**Comment by Bosn** [comment]
不至于啊，Module数量要是int都装不下，那也太厉害了，我查下，不像是这个问题。

**Comment by Bosn** [comment]
你这是自己搭建的服务器？线上 rap2.taobao.org没复现。

**Comment by 307guojiawei** [comment]
不止在这处，在Properties,Interfaces和Modules中的Priority都有这个问题，我实测了一下，插入的数据中Priority字段的值大概是`1526351461145`这个样子

**Comment by 307guojiawei** [comment]
数据库中执行
‘’‘
alter table Properties modify column priority bigint(50) not null default '1';
alter table Interfaces modify column priority bigint(50) not null default '1';
alter table Modules modify column priority bigint(50) not null default '1';
’‘’
可以解决问题

**Comment by 307guojiawei** [comment]
我的Mysql 版本是:mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64)，可能是版本问题？

**Comment by blackdog1987** [comment]
参考#167

**Comment by Bosn** [comment]
@307guojiawei 好奇怪，你们出问题的是在自己部署的机器上么？还是rap2.taobao.org呢？

为什么我自己本地测试、和线上rap2跑都不复现呢。
不过数据类型我紧急更新下，着急的同学自己部署的，也可以自行修改下priority类型，变为bigint

**Comment by 307guojiawei** [comment]
@Bosn 多谢多谢，问题是出在自己部署的机器上

**Comment by Bosn** [comment]
@307guojiawei 已经定位并解决。

代码更新：https://github.com/thx/rap2-delos/commit/c20bc97f2497887816cb964a0fb4787fd3bb1573

数据库变更脚本：https://github.com/thx/rap2-delos/blob/master/database/v2018_5_15_change.sql
