### ISSUE TITLE
不断提示 Error: Cannot find module './migrate'

### ISSUE THREAD

**Issue by coagent** [thx/rap2-delos#174]
npm start 后通过 pm2 logs 0 查看日志，出现以下错误日志：

```
0|rap-serv | module.js:540
0|rap-serv |     throw err;
0|rap-serv |     ^
0|rap-serv | Error: Cannot find module './migrate'
0|rap-serv |     at Function.Module._resolveFilename (module.js:538:15)
0|rap-serv |     at Function.Module._load (module.js:468:25)
0|rap-serv |     at Module.require (module.js:587:17)
0|rap-serv |     at require (internal/module.js:11:18)
0|rap-serv |     at Object.<anonymous> (/opt/rap2-delos/dist/routes/index.js:10:1)
0|rap-serv |     at Module._compile (module.js:643:30)
0|rap-serv |     at Object.Module._extensions..js (module.js:654:10)
0|rap-serv |     at Module.load (module.js:556:32)
0|rap-serv |     at tryModuleLoad (module.js:499:12)
0|rap-serv |     at Function.Module._load (module.js:491:3)
0|rap-serv |     at Module.require (module.js:587:17)
0|rap-serv |     at require (internal/module.js:11:18)
0|rap-serv |     at Object.<anonymous> (/opt/rap2-delos/dist/scripts/app.js:17:18)
0|rap-serv |     at Module._compile (module.js:643:30)
0|rap-serv |     at Object.Module._extensions..js (module.js:654:10)
0|rap-serv |     at Module.load (module.js:556:32)
0|rap-serv |     at tryModuleLoad (module.js:499:12)
0|rap-serv |     at Function.Module._load (module.js:491:3)
0|rap-serv |     at Module.require (module.js:587:17)
0|rap-serv |     at require (internal/module.js:11:18)
0|rap-serv |     at Object.<anonymous> (/opt/rap2-delos/dist/scripts/worker.js:3:15)
0|rap-serv |     at Module._compile (module.js:643:30)
0|rap-serv |     at Object.Module._extensions..js (module.js:654:10)
0|rap-serv |     at Module.load (module.js:556:32)
0|rap-serv |     at tryModuleLoad (module.js:499:12)
0|rap-serv |     at Function.Module._load (module.js:491:3)
0|rap-serv |     at Function.Module.runMain (module.js:684:10)
0|rap-serv |     at startup (bootstrap_node.js:187:16)
0|rap-serv | [2018-05-15 06:42:31.383] master#3462 worker#3750 has disconnected.
0|rap-serv | [2018-05-15 06:42:31.384] master#3462 worker#3750 died (1). restarting...
0|rap-serv | Tue, 15 May 2018 06:42:31 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
```

**Comment by coagent** [comment]
尝试执行 npm install -g migrate，仍然报这个错误，导致无法启动应用。

**Comment by coagent** [comment]
我拉取 master 最新的代码，源代码里有这个 migrate.ts 文件。

**Comment by lk125454242** [comment]
这个报错的位置 是/src/routes/index.ts 里面的 require('./migrate'), 等待解决

**Comment by Bosn** [comment]
@lk125454242 同上啊，最新版有这个文件的，检查一下，不是最新的更新一下

**Comment by iimmz** [comment]
路径问题，修改require('./migrate')为require('../service/migrate')

**Comment by Bosn** [comment]
@hqwlkj 抱歉我搞错了问题，service/migrate是有的，routes/migrate确实后来我已经删掉了。相应代码已更新至master哦。npm run build会删掉dist执行全量部署。
