### ISSUE TITLE
新建仓库BUG：点击创建无反应

### ISSUE THREAD

**Issue by AnInputForce** [thx/rap2-delos#201]
后端delos使用的docker镜像 tag1.11或自行build的master最新代码
前端nginx + build后的静态页面

无论是直接创建仓库还是在团队创建仓库，均是输入完毕后多次点击创建无反应，弹出窗口也不关闭。
取消后，页面刷新，发现已创建同名仓库若干；
编辑仓库可以正常编辑。

应该是后端报错了：

` SequelizeDatabaseError: Unknown column 'Logger.creatorId' in 'field list'
at Query.formatError (/app/node_modules/_sequelize@4.37.10@sequelize/lib/dialects/mysql/query.js:247:16)
at Query.handler [as onResult] (/app/node_modules/_sequelize@4.37.10@sequelize/lib/dialects/mysql/query.js:68:23)
at Query.Command.execute (/app/node_modules/_mysql2@1.5.3@mysql2/lib/commands/command.js:30:12)
at Connection.handlePacket (/app/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:502:28)
at PacketParser.onPacket (/app/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:81:16)
at PacketParser.executeStart (/app/node_modules/_mysql2@1.5.3@mysql2/lib/packet_parser.js:77:14)
at Socket. (/app/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:89:29)
at Socket.emit (events.js:180:13)
at addChunk (_stream_readable.js:274:12)
at readableAddChunk (_stream_readable.js:261:11)
at Socket.Readable.push (_stream_readable.js:218:10)
at TCP.onread (net.js:581:20)

SequelizeDatabaseError: Field 'createdAt' doesn't have a default value
at Query.formatError (/app/node_modules/_sequelize@4.37.10@sequelize/lib/dialects/mysql/query.js:247:16)
at Query.handler [as onResult] (/app/node_modules/_sequelize@4.37.10@sequelize/lib/dialects/mysql/query.js:68:23)
at Query.Command.execute (/app/node_modules/_mysql2@1.5.3@mysql2/lib/commands/command.js:30:12)
at Connection.handlePacket (/app/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:502:28)
at PacketParser.onPacket (/app/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:81:16)
at PacketParser.executeStart (/app/node_modules/_mysql2@1.5.3@mysql2/lib/packet_parser.js:77:14)
at Socket. (/app/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:89:29)
at Socket.emit (events.js:180:13)
at addChunk (_stream_readable.js:274:12)
at readableAddChunk (_stream_readable.js:261:11)
at Socket.Readable.push (_stream_readable.js:218:10)
at TCP.onread (net.js:581:20)

`

**Comment by Bosn** [comment]
初始化不对啊，亲。creatorId可以看`src/models/bo`是存在的哟，mysql查一下`DESC logger`看看返回了什么呢

**Comment by AnInputForce** [comment]
谢谢大神回复，确实是我自己多执行了一些SQL。
能否给一个目录来初始化生产环境？
现在若登录容器执行 script/init 就会扔一堆mock数据进来。

自己删了删，勉强能用了。期待官方有正式 初始化docker容器 生产环境的脚步
