### ISSUE TITLE
新增接口参数Out of range value for column 'priority' at row 1

### ISSUE THREAD

**Issue by dafanshu** [thx/rap2-delos#222]
xxx POST /properties/update?itf=138 500 30ms -
  SequelizeDatabaseError: Out of range value for column 'priority' at row 1
      at Query.formatError (/app/node_modules/sequelize/lib/dialects/mysql/query.js:228:16)
      at Query.connection.query [as onResult] (/app/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
      at Query.Command.execute (/app/node_modules/mysql2/lib/commands/command.js:30:12)
      at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:515:28)
      at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:94:16)
      at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:77:14)
      at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:102:29)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:607:20)

**Comment by Bosn** [comment]
参考DATABASE/下的迁移文件，检查版本问题。
