### ISSUE TITLE
按描述，走开发模式部署，有些小问题

### ISSUE THREAD

**Issue by new0211032** [thx/rap2-delos#24]
初始化之后，运行`npm run create-db`
脚本并不是根据【/config/config.**dev**.js】里的配置来运行，而是【/config/config.**prod**.js】。

如果【/config/config.**prod**.js】里没有配上生产环境的数据库信息，直接报错如下：
`Unable to connect to the database: { SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake._callback (/Users/coding/rap2/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:83:20)
    at Handshake.Sequence.end (/Users/coding/rap2/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Handshake.ErrorPacket (/Users/coding/rap2/node_modules/mysql/lib/protocol/sequences/Handshake.js:132:8)
    at Protocol._parsePacket (/Users/coding/rap2/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/coding/rap2/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/coding/rap2/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/coding/rap2/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'SequelizeAccessDeniedError',
  message: 'ER_ACCESS_DENIED_ERROR: Access denied for user \'root\'@\'localhost\' (using password: NO)',`

不是很懂node，不知道在哪里可以把这个依赖配置改成对应环境的文件，部署描述也没有细说。

**Comment by Bosn** [comment]
npm run dev => 会走开发模式
npm start 或者 npm run start 会走生产模式

README中有中文的文档说明哦，node学习要自己学学啦，我也没办法一两句给您说清楚哟。
