### ISSUE TITLE
升级RAP2后无法访问仓库 SequelizeDatabaseError: Unknown column 'interface.status' in 'field list'

### ISSUE THREAD

**Issue by gzliudan** [thx/rap2-delos#253]
**BUG描述**
升级RAP2的源代码后，能登录，但点仓库后新页面不显示。是否需要再次执行创建数据库的脚本？能否保留老数据?

**自建服务器
centos 7.2

**附加信息**
  SequelizeDatabaseError: Unknown column 'interface.status' in 'field list'
      at Query.formatError (/usr/local/share/RAP2/rap2-delos/node_modules/_sequelize@4.38.0@sequelize/lib/dialects/mysql/query.js:247:16)
      at Query.handler [as onResult] (/usr/local/share/RAP2/rap2-delos/node_modules/_sequelize@4.38.0@sequelize/lib/dialects/mysql/query.js:68:23)
      at Query.Command.execute (/usr/local/share/RAP2/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/commands/command.js:30:12)
      at Connection.handlePacket (/usr/local/share/RAP2/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:502:28)
      at PacketParser.onPacket (/usr/local/share/RAP2/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:81:16)
      at PacketParser.executeStart (/usr/local/share/RAP2/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/packet_parser.js:77:14)
      at Socket.<anonymous> (/usr/local/share/RAP2/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:89:29)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:597:20)

**Comment by gzliudan** [comment]
根据文件 v2.6_change_20180705.sql ，执行 ALTER TABLE `Interfaces`  ADD COLUMN `status` INT(10) NULL DEFAULT 200; 就修复了这个问题。
