### ISSUE TITLE
导入出错SequelizeDatabaseError: Data truncated for column 'type' at row 1

### ISSUE THREAD

**Issue by LvJianfeng** [thx/rap2-delos#270]
**BUG描述**
```shell
SequelizeDatabaseError: Data truncated for column 'type' at row 1
      at Query.formatError (/usr/local/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
      at Query.handler [as onResult] (/usr/local/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
      at Query.Command.execute (/usr/local/rap2-delos/node_modules/mysql2/lib/commands/command.js:30:12)
      at Connection.handlePacket (/usr/local/rap2-delos/node_modules/mysql2/lib/connection.js:502:28)
      at PacketParser.onPacket (/usr/local/rap2-delos/node_modules/mysql2/lib/connection.js:81:16)
      at PacketParser.executeStart (/usr/local/rap2-delos/node_modules/mysql2/lib/packet_parser.js:77:14)
      at Socket.<anonymous> (/usr/local/rap2-delos/node_modules/mysql2/lib/connection.js:89:29)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:597:20)
  From previous event:
      at Query.run (/usr/local/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
      at Promise.try.then.connection (/usr/local/rap2-delos/node_modules/sequelize/lib/sequelize.js:558:20)
  From previous event:
      at Promise.resolve.retryParameters (/usr/local/rap2-delos/node_modules/sequelize/lib/sequelize.js:555:8)
      at /usr/local/rap2-delos/node_modules/retry-as-promised/index.js:39:21
      at retryAsPromised (/usr/local/rap2-delos/node_modules/retry-as-promised/index.js:29:10)
      at Sequelize.query (/usr/local/rap2-delos/node_modules/sequelize/lib/sequelize.js:454:28)
      at QueryInterface.insert (/usr/local/rap2-delos/node_modules/sequelize/lib/query-interface.js:901:27)
      at Promise.try.then.then.then (/usr/local/rap2-delos/node_modules/sequelize/lib/model.js:3695:53)
      at runCallback (timers.js:810:20)
      at tryOnImmediate (timers.js:768:5)
      at processImmediate [as _immediateCallback] (timers.js:745:5)
  From previous event:
      at Property.save (/usr/local/rap2-delos/node_modules/sequelize/lib/model.js:3671:8)
      at Function.create (/usr/local/rap2-delos/node_modules/sequelize/lib/model.js:2035:8)
      at Function._target.(anonymous function) [as create] (/usr/local/rap2-delos/node_modules/sequelize-typescript/lib/models/BaseModel.js:36:41)
      at Object.<anonymous> (/usr/local/rap2-delos/dist/routes/repository.js:779:47)
      at Generator.next (<anonymous>)
      at fulfilled (/usr/local/rap2-delos/dist/routes/repository.js:3:58)
      at <anonymous>
```
**自建服务器**
如果是自建服务器，提供操作系统版本
Centos7 

**附加信息**
```json
{
    "msgEx": {
        "infos": {
            "loanOrderList": [
                {
                    "phone": "",
                    "monthliabilities": "",
                    "purposeName": "",
                    "updatetime": null,
                    "beforetaxsalary": "",
                    "id": null,
                    "profession": "",
                    "projectName": "",
                    "createtime": "2018-03-16",
                    "new": true,
                    "isShowModifyCard": "",
                    "bankName": "",
                    "serialNumber": "",
                    "sort": "",
                    "subbranch": "",
                    "bankInfoId": "",
                    "operatorcode": "",
                    "isShowStatus": "1",
                    "btnStatus": "",
                    "accNo": "",
                    "flowstatusValue": "0",
                    "property": "",
                    "city": "",
                    "status": "1",
                    "order": "",
                    "cityName": "",
                    "cid": 0,
                    "projectCode": "",
                    "applylimit": "100",
                    "flowstatus": "稍等",
                    "isProject": "",
                    "jumpUrl": "",
                    "reason": "",
                    "purpose": "",
                    "ordernum": "20180726",
                    "gimageUrl": "",
                    "memo": "",
                    "applyDate": "2018-07-16",
                    "deadline": "5",
                    "isRed": ""
                }
            ],
            "total": 1
        },
        "status": "0",
        "respDesc": "操作成功"
    },
    "code": "0000"
}
```

**Comment by Bosn** [comment]
测试最新master无问题，参考database/*.sql 是不是老版本升级后用了新的代码，但是database中的数据库迁移脚本没执行。

**Comment by AtrisMio** [comment]
@LvJianfeng 我也遇到了同样的问题，可能你插入的数据中含有Null类型

如果要兼容的话，需要改数据库和他的业务代码，具体可以看我提的pr
#383

**Comment by iwin4aids** [comment]
我也遇到和lz同样的问题，我感觉是导入的json文件比较大就会出这个问题

**Comment by iwin4aids** [comment]
> 测试最新master无问题，参考database/*.sql 是不是老版本升级后用了新的代码，但是database中的数据库迁移脚本没执行。

确认你测试过吗? 我用11月的master都可以重现这个问题，依然没有解决

**Comment by AtrisMio** [comment]
@iwin4aids 其实是导入json的时候里面有值是null，然后他前端又没做handle，认为是Null类型，后端又不让存Null类型，就报错了。。。

**Comment by iwin4aids** [comment]
> @iwin4aids 其实是导入json的时候里面有值是null，然后他前端又没做handle，认为是Null类型，后端又不让存Null类型，就报错了。。。

我认为应该merge一下你的pr， json里面有null很正常啊···

**Comment by njleonzhang** [comment]
同样的问题啊，那么为什么 @AtrisMio 不被 merge 呢？

**Comment by MapleImage** [comment]
试试这个 /src/actions/property.js代码中修改值为空的属性type值默认为String就好了
```
export const updateProperties = (itf, properties, summary, onResolved) => ({
  type: 'PROPERTIES_UPDATE',
  itf,
  properties: properties.map(item=>{
    return {...item, type: item.type==='Null' ? 'String': item.type}
  }),
  summary,
  onResolved
})
```
