### ISSUE TITLE
Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by latel** [thx/rap2-delos#306]
**BUG描述**
mysql是不是有版本要求

**复现步骤**
npm run client-db

**期望结果**
ok

**实际结果**
error

**截图**

**环境**
macos +docker[mysql:8.0]

**附加信息**
```
➜  rap2-delos git:(master) ✗ npm run create-db

> rap2-delos@1.0.0 create-db /Users/kevinnwang/codes/rap2-delos
> cross-env NODE_ENV=development node dist/scripts/init

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
Unable to connect to the database: { SequelizeConnectionError: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Utils.Promise.tap.then.catch.err (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
From previous event:
    at ConnectionManager.connect (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at ConnectionManager._connect (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/kevinnwang/codes/rap2-delos/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/kevinnwang/codes/rap2-delos/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:783:17)
    at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/models/sequelize.js:24:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/scripts/init/delos.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/scripts/init/index.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
  name: 'SequelizeConnectionError',
  parent:
   { Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client
       at Packet.asError (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/packets/packet.js:714:13)
       at ClientHandshake.Command.execute (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/commands/command.js:28:22)
       at Connection.handlePacket (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/connection.js:513:28)
       at PacketParser.onPacket (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/connection.js:81:16)
       at PacketParser.executeStart (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/packet_parser.js:76:14)
       at Socket.<anonymous> (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/connection.js:89:29)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at Socket.Readable.push (_stream_readable.js:219:10)
       at TCP.onread (net.js:639:20)
   From previous event:
       at ConnectionManager.connect (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:12)
       at sequelize.runHooks.then (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
       at runCallback (timers.js:696:18)
       at tryOnImmediate (timers.js:667:5)
       at processImmediate (timers.js:649:5)
   From previous event:
       at ConnectionManager._connect (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
       at ConnectionManager.getConnection (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
       at Promise.try (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:554:34)
   From previous event:
       at Promise.resolve.retryParameters (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:454:64)
       at /Users/kevinnwang/codes/rap2-delos/node_modules/retry-as-promised/index.js:39:21
       at retryAsPromised (/Users/kevinnwang/codes/rap2-delos/node_modules/retry-as-promised/index.js:29:10)
       at Sequelize.query (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:454:28)
       at Sequelize.authenticate (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:783:17)
       at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/models/sequelize.js:24:11)
       at Module._compile (internal/modules/cjs/loader.js:689:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at require (internal/modules/cjs/helpers.js:20:18)
       at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/scripts/init/delos.js:10:21)
       at Module._compile (internal/modules/cjs/loader.js:689:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at require (internal/modules/cjs/helpers.js:20:18)
       at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/scripts/init/index.js:10:17)
       at Module._compile (internal/modules/cjs/loader.js:689:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
       at startup (internal/bootstrap/node.js:266:19)
     code: 'ER_NOT_SUPPORTED_AUTH_MODE',
     errno: 1251,
     sqlState: '08004',
     sqlMessage:
      'Client does not support authentication protocol requested by server; consider upgrading MySQL client' },
  original:
   { Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client
       at Packet.asError (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/packets/packet.js:714:13)
       at ClientHandshake.Command.execute (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/commands/command.js:28:22)
       at Connection.handlePacket (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/connection.js:513:28)
       at PacketParser.onPacket (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/connection.js:81:16)
       at PacketParser.executeStart (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/packet_parser.js:76:14)
       at Socket.<anonymous> (/Users/kevinnwang/codes/rap2-delos/node_modules/mysql2/lib/connection.js:89:29)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at Socket.Readable.push (_stream_readable.js:219:10)
       at TCP.onread (net.js:639:20)
   From previous event:
       at ConnectionManager.connect (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:12)
       at sequelize.runHooks.then (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
       at runCallback (timers.js:696:18)
       at tryOnImmediate (timers.js:667:5)
       at processImmediate (timers.js:649:5)
   From previous event:
       at ConnectionManager._connect (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
       at ConnectionManager.getConnection (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
       at Promise.try (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:554:34)
   From previous event:
       at Promise.resolve.retryParameters (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:454:64)
       at /Users/kevinnwang/codes/rap2-delos/node_modules/retry-as-promised/index.js:39:21
       at retryAsPromised (/Users/kevinnwang/codes/rap2-delos/node_modules/retry-as-promised/index.js:29:10)
       at Sequelize.query (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:454:28)
       at Sequelize.authenticate (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:783:17)
       at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/models/sequelize.js:24:11)
       at Module._compile (internal/modules/cjs/loader.js:689:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at require (internal/modules/cjs/helpers.js:20:18)
       at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/scripts/init/delos.js:10:21)
       at Module._compile (internal/modules/cjs/loader.js:689:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at require (internal/modules/cjs/helpers.js:20:18)
       at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/scripts/init/index.js:10:17)
       at Module._compile (internal/modules/cjs/loader.js:689:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
       at startup (internal/bootstrap/node.js:266:19)
     code: 'ER_NOT_SUPPORTED_AUTH_MODE',
     errno: 1251,
     sqlState: '08004',
     sqlMessage:
      'Client does not support authentication protocol requested by server; consider upgrading MySQL client' } }
(node:73114) UnhandledPromiseRejectionWarning: SequelizeConnectionError: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Utils.Promise.tap.then.catch.err (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
From previous event:
    at ConnectionManager.connect (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at ConnectionManager._connect (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/kevinnwang/codes/rap2-delos/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/kevinnwang/codes/rap2-delos/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/kevinnwang/codes/rap2-delos/node_modules/sequelize/lib/sequelize.js:783:17)
    at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/models/sequelize.js:24:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/scripts/init/delos.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/kevinnwang/codes/rap2-delos/dist/scripts/init/index.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
(node:73114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function withouta catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:73114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ganl** [comment]
Mysql改为5.7.23即可，前两天也遇到了
最开始用的tag：latest
[https://github.com/ganl/rap2-docker/blob/master/env-example#L80]()

**Comment by Bosn** [comment]
如字面意思及楼上的恢复，版本过低导致。

**Comment by cocoasui** [comment]
MySql8 加密方式变更导致，设定加密方式为旧的 mysql_native_password 方式。
参考 [https://blog.csdn.net/why154285/article/details/81062689](https://blog.csdn.net/why154285/article/details/81062689 )
