### ISSUE TITLE
rap2-dolores 部署run test/run dev出错

### ISSUE THREAD

**Issue by Zooc** [thx/rap2-delos#313]
**BUG描述**
1. 执行npm run test 出现一下错误提示
standard: Use JavaScript Standard Style (https://standardjs.com)
  /usr/src/rap2-dolores/src/relatives/effects/interface.js:86:7: 'alert' is not defined.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 linter: `standard --fix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 linter script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T15_35_37_800Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 test: `npm run linter`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T15_35_37_821Z-debug.log

2.执行 npm run dev ， 出现以下错误提示
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/src/rap2-dolores/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/usr/src/rap2-dolores/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/usr/src/rap2-dolores/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/src/rap2-dolores/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/src/rap2-dolores/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/src/rap2-dolores/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/src/rap2-dolores/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 build-css: `node-sass src/ -o src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 build-css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T15_36_53_584Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 watch-css: `npm run build-css && node-sass src/ -o src/ --watch --recursive`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 watch-css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T15_36_53_629Z-debug.log
ERROR: "watch-css" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 start: `npm-run-all -p watch-css start-js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T15_36_53_684Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 dev: `npm run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T15_36_53_703Z-debug.log

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
自建服务器，centos7 64位
* 如果是前端错误，请提供浏览器版本
node 8.9.4
* 其它可能帮助我们排查问题的环境信息
原以为node 版本问题，最开始用10，但后来切换8.9.4依然出问题

**附加信息**

**Comment by Zooc** [comment]
原来是自己的内存不够，增加了swap内存后就好了。http://www.10tiao.com/html/371/201703/2669790609/1.html
