### ISSUE TITLE
npm run create-db error

### ISSUE THREAD

**Issue by fengallan0** [thx/rap2-delos#322]
这是我的config.dev.ts配置文件
import { IConfigOptions } from "../types";

let config: IConfigOptions = {
  version: '2.3',
  serve: {
    port: 8080,
  },
  keys: ['some secret hurr'],
  session: {
    key: 'rap2:sess',
  },
  db: {
    dialect: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'root',
    password: 'Feng1900',
    database: 'RAP2_DELOS_APP',
    pool: {
      max: 5,
      min: 0,
      idle: 10000,
    },
    logging: false,
  },
  redis: {
    isRedisCluster: true,
     nodes: [{
       port: 6379,
       host: '127.0.0.1',
     },
    // {
    //   port: 6380,
    //   host: '*.*.*',
    // },
    // {
    //   port: 6381,
    //   host: '*.*.*',
    // }
    ],
     redisOptions: {
       password: 'Vvic2018redis',
     }
  }

}

export default config

但是执行npm run create-db 就一直报错，iosredis，请问下是什么问题？谢谢！
[ioredis] Unhandled error event: Error: Failed to refresh slots cache.
    at tryNode (/data/rap2-delos/node_modules/ioredis/lib/cluster/index.js:375:19)
    at /data/rap2-delos/node_modules/ioredis/lib/cluster/index.js:387:9
    at /data/rap2-delos/node_modules/ioredis/lib/cluster/index.js:591:14
    at run (/data/rap2-delos/node_modules/ioredis/lib/utils/index.js:153:16)
    at tryCatcher (/data/rap2-delos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/data/rap2-delos/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/data/rap2-delos/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/data/rap2-delos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/data/rap2-delos/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/data/rap2-delos/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/data/rap2-delos/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/data/rap2-delos/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/data/rap2-delos/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by Bosn** [comment]
看起来是redis安装的问题，详细看下README上面的安装要求。
具体操作系统环境和数据库redis安装问题不在本区解决范围哦亲。
