### ISSUE TITLE
访问仓库出现500错误

### ISSUE THREAD

**Issue by gzliudan** [thx/rap2-delos#348]
Request URL: http://10.64.228.141:8080/repository/get?id=31

Status Code: 500 Internal Server Error

文件 /root/.pm2/logs/rap-server-delos-error-0.log内容如下：

Fri, 28 Sep 2018 13:06:21 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/_sequelize@4.38.0@sequelize/lib/sequelize.js:242:13
Fri, 28 Sep 2018 13:06:21 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/_sequelize@4.38.0@sequelize/lib/sequelize.js:242:13
Fri, 28 Sep 2018 13:06:21 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/_sequelize@4.38.0@sequelize/lib/sequelize.js:242:13
[2018-09-28 13:06:21.608] master#26965 worker#26987 is now connected to null:8080.
Fri, 28 Sep 2018 13:06:21 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/_sequelize@4.38.0@sequelize/lib/sequelize.js:242:13
[2018-09-28 13:06:21.667] master#26965 worker#26988 is now connected to null:8080.
[2018-09-28 13:06:21.681] master#26965 worker#27003 is now connected to null:8080.
[2018-09-28 13:06:21.727] master#26965 worker#26993 is now connected to null:8080.

  SequelizeDatabaseError: Unknown column 'modules->interfaces->properties.required' in 'field list'
      at Query.formatError (/usr/local/share/RAP2/rap2-delos/node_modules/_sequelize@4.38.0@sequelize/lib/dialects/mysql/query.js:247:16)
      at Query.handler [as onResult] (/usr/local/share/RAP2/rap2-delos/node_modules/_sequelize@4.38.0@sequelize/lib/dialects/mysql/query.js:68:23)
      at Query.Command.execute (/usr/local/share/RAP2/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/commands/command.js:30:12)
      at Connection.handlePacket (/usr/local/share/RAP2/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:502:28)
      at PacketParser.onPacket (/usr/local/share/RAP2/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:81:16)
      at PacketParser.executeStart (/usr/local/share/RAP2/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/packet_parser.js:77:14)
      at Socket.<anonymous> (/usr/local/share/RAP2/rap2-delos/node_modules/_mysql2@1.5.3@mysql2/lib/connection.js:89:29)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:597:20)

**Comment by CaptainDF** [comment]
![image](https://user-images.githubusercontent.com/16588076/46215377-d230cd80-c36f-11e8-9b39-3bad0e500099.png)
这两个sql执行一下
