### ISSUE TITLE
redis 添加密码验证, 创建数据库的时候报错

### ISSUE THREAD

**Issue by lihuiby** [thx/rap2-delos#355]
**BUG描述**
redis使用了密码验证, 在npm run create-db的时候就报错了, 修改了配置文件 src/config/config.dev.ts 的redisOptions.password 选项, 还是报错.

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
ReplyError: NOAUTH Authentication required.
    at new Command (/home/git/rap2-delos/node_modules/redis/lib/command.js:12:22)
    at RedisClient.info (/home/git/rap2-delos/node_modules/redis/lib/individualCommands.js:169:39)
    at RedisClient.ready_check (/home/git/rap2-delos/node_modules/redis/index.js:534:10)
    at RedisClient.on_connect (/home/git/rap2-delos/node_modules/redis/index.js:428:14)
    at Socket.<anonymous> (/home/git/rap2-delos/node_modules/redis/index.js:268:14)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:187:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1147:10)
Emitted 'error' event at:
    at RedisClient.on_info_cmd (/home/git/rap2-delos/node_modules/redis/index.js:496:14)
    at /home/git/rap2-delos/node_modules/redis/index.js:535:14
    at Object.callbackOrEmit [as callback_or_emit] (/home/git/rap2-delos/node_modules/redis/lib/utils.js:89:9)
    at /home/git/rap2-delos/node_modules/redis/lib/individualCommands.js:157:15
    at Object.callbackOrEmit [as callback_or_emit] (/home/git/rap2-delos/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/home/git/rap2-delos/node_modules/redis/index.js:706:11)
    at JavascriptRedisParser.returnError (/home/git/rap2-delos/node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (/home/git/rap2-delos/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/home/git/rap2-delos/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-delos@1.0.0 create-db: `cross-env NODE_ENV=development node dist/scripts/init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-delos@1.0.0 create-db script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Bosn** [comment]
mysql配置及安装错误，错误信息上看是mysql授权错误。关于如何使用mysql请移步mysql相关论坛或群中咨询哦。

**Comment by lihuiby** [comment]
是mysql? 不是redis吗? 如果, redis设置了密码, 配置文件中有哪些属性是需要注意的吗?

**Comment by pangtengfei** [comment]
应该是redis密码不对，加个password配置项

**Comment by SummerWindL** [comment]
兄弟这个问题你解决了吗？从错误看应该就是redis设置了密码，没验证不给登录的

**Comment by SummerWindL** [comment]
> 应该是redis密码不对，加个password配置项

我加了password还是报这个错误

**Comment by zdxu** [comment]
> > 应该是redis密码不对，加个password配置项
> 
> 我加了password还是报这个错误

改完密码要记得 npm run build
