### ISSUE TITLE
更新代码配置redis密码后，后台一直报错

### ISSUE THREAD

**Issue by flyCatOne** [thx/rap2-delos#363]
后台一直循环刷这个错误:`[ioredis] Unhandled error event: Error: Failed to refresh slots cache.
    at tryNode (D:\git_rap2_redoles\rap2-delos\node_modules\ioredis\lib\cluster\index.js:375:19)
    at D:\git_rap2_redoles\rap2-delos\node_modules\ioredis\lib\cluster\index.js:387:9
    at D:\git_rap2_redoles\rap2-delos\node_modules\ioredis\lib\cluster\index.js:591:14
    at run (D:\git_rap2_redoles\rap2-delos\node_modules\ioredis\lib\utils\index.js:153:16)
    at tryCatcher (D:\git_rap2_redoles\rap2-delos\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (D:\git_rap2_redoles\rap2-delos\node_modules\bluebird\js\release\nodeify.js:35:34)
    at Promise._settlePromise (D:\git_rap2_redoles\rap2-delos\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (D:\git_rap2_redoles\rap2-delos\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\git_rap2_redoles\rap2-delos\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (D:\git_rap2_redoles\rap2-delos\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\git_rap2_redoles\rap2-delos\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\git_rap2_redoles\rap2-delos\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)`

dev 配置如下：
`import { IConfigOptions } from "../types";

let config: IConfigOptions = {
  version: '2.3',
  serve: {
    port: 8090,
  },
  keys: ['some secret hurr'],
  session: {
    key: 'rap2:sess',
  },
  db: {
    dialect: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'root',
    password: 'root',
    database: 'RAP2_DELOS_APP',
    pool: {
      max: 5,
      min: 0,
      idle: 10000,
    },
    logging: false,
  },
  redis: {
    isRedisCluster: true,
    nodes: [{
      port: 6379,
      host: '127.0.0.1',
    }
    // ,
    // {
    //   port: 6379,
    //   host: '127.0.0.1',
    // },
    // {
    //   port: 6379,
    //   host: '127.0.0.1',
    // }
  ],
    redisOptions: {
      password:'123456',
    }
  }
}

export default config
`

**Comment by Bosn** [comment]
本repo不负责解决redis安装/配置相关问题哟亲。
