### ISSUE TITLE
查看全部团队无法获取

### ISSUE THREAD

**Issue by wade246** [thx/rap2-delos#404]
**BUG描述**
无法获取全部团队信息

**复现步骤**
由仓库切换Tab到团队，想要获取全部团队，发现无法获取

**期望结果**
能读取到全部团队信息

**实际结果**
服务器端查看报错信息：
Unhandled rejection SequelizeDatabaseError: Unknown column 'undefined' in 'where clause'
    at Query.formatError (C:\Windows\System32\rap2-delos\node_modules\sequelize\lib\dialects\mysql\query.js:247:16)
    at Query.handler [as onResult] (C:\Windows\System32\rap2-delos\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.execute (C:\Windows\System32\rap2-delos\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (C:\Windows\System32\rap2-delos\node_modules\mysql2\lib\connection.js:455:32)
    at PacketParser.onPacket (C:\Windows\System32\rap2-delos\node_modules\mysql2\lib\connection.js:73:18)
    at PacketParser.executeStart (C:\Windows\System32\rap2-delos\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Windows\System32\rap2-delos\node_modules\mysql2\lib\connection.js:80:31)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
From previous event:
    at Query.run (C:\Windows\System32\rap2-delos\node_modules\sequelize\lib\dialects\mysql\query.js:57:12)
    at Promise.try.then.connection (C:\Windows\System32\rap2-delos\node_modules\sequelize\lib\sequelize.js:558:20)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
From previous event:
    at Promise.resolve.retryParameters (C:\Windows\System32\rap2-delos\node_modules\sequelize\lib\sequelize.js:555:8)
    at C:\Windows\System32\rap2-delos\node_modules\retry-as-promised\index.js:39:21
    at retryAsPromised (C:\Windows\System32\rap2-delos\node_modules\retry-as-promised\index.js:29:10)
    at Sequelize.query (C:\Windows\System32\rap2-delos\node_modules\sequelize\lib\sequelize.js:454:28)
    at resolve (C:\Windows\System32\rap2-delos\dist\service\organization.js:65:33)
    at new Promise (<anonymous>)
    at Function.getAllOrganizationIdListNum (C:\Windows\System32\rap2-delos\dist\service\organization.js:64:16)
    at Object.<anonymous> (C:\Windows\System32\rap2-delos\dist\routes\organization.js:43:48)
    at Generator.next (<anonymous>)
    at C:\Windows\System32\rap2-delos\dist\routes\organization.js:6:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Windows\System32\rap2-delos\dist\routes\organization.js:2:12)
    at router_1.default.get (C:\Windows\System32\rap2-delos\dist\routes\organization.js:40:53)
    at dispatch (C:\Windows\System32\rap2-delos\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Windows\System32\rap2-delos\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Windows\System32\rap2-delos\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Windows\System32\rap2-delos\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Windows\System32\rap2-delos\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Windows\System32\rap2-delos\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (C:\Windows\System32\rap2-delos\node_modules\koa-compose\index.js:42:32)
    at C:\Windows\System32\rap2-delos\node_modules\koa-body\index.js:110:14

**截图**

**环境**
* 自建环境，win10  处理器：Intel(R)_Xeon(R)_CPU E5620  @ 2.40GHz
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by eyis** [comment]
没有复现
