### ISSUE TITLE
修改接口无法保存，服务端错误，响应500

### ISSUE THREAD

**Issue by veryWrong** [thx/rap2-delos#408]
**BUG描述**
编辑接口保存的时候服务端报错

**复现步骤**
点击编辑接口->点击保存按钮

**期望结果**
保存修改后的结果

**实际结果**
无法保存修改后的结果

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
服务端报错信息如下：
SequelizeDatabaseError: Data truncated for column 'type' at row 1
      at Query.formatError (/app/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
      at Query.handler [as onResult] (/app/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
      at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:30:14)
      at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:455:32)
      at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:73:18)
      at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:80:31)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:607:20)

**Comment by njleonzhang** [comment]
遇到同样的问题。你解决了么？

**Comment by AnInputForce** [comment]
我是升级了六个月前的rap2到现在的版本。发现无法编辑。
仔细梳理，应该是变更完字段，没有更新redis缓存。清空缓存后，问题解决，可以编辑。验证中。
不知道你们是不是这种情况，仅供参考。

查看release目录下的md：

> # V2.6 更新说明 2018-7-5

> * 数据库字段变更请执行 `datbase/v2.6***`
> * 因字段变更，需要清空redis缓存
>  1. 运行redis-cli
>   2. 执行 `flushall` 命令清空缓存

**Comment by njleonzhang** [comment]
@AnInputForce 谢谢已经解决，也是数据库的问题。

**Comment by enngch** [comment]
@njleonzhang 能具体说下是怎么解决的么

**Comment by njleonzhang** [comment]
@enngch 数据库配置的有问题。

你使用下面的这个命令，起一下服务端，在 console 里应该能看到报错的具体 log。
```
 NODE_ENV=production node dist/dispatch.js
```

**Comment by enngch** [comment]
@njleonzhang 好的谢谢，我这边刚检查了下，数据库配置是正常的，除了提示 Model.findById 和beforeDelete hook 被弃用，没有其他错误，准备重新部署下，看看问题是不是还存在...

**Comment by SuperTommy007** [comment]
有时候保存接口还是会出现这个问题，上面的解决方案我都检查过了，数据库是最新的，redis缓存也清空了，也不是数据库名的问题
