### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by dly667** [thx/rap2-delos#421]
**BUG描述**
[dly@VM_0_16_centos rap2-delos]$ sudo npm run dev

> rap2-delos@1.0.0 dev /home/dly/rap2-delos
> cross-env NODE_ENV=development nodemon --watch scripts --watch dist dist/scripts/dev.js

[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: scripts /home/dly/rap2-delos/dist/**/*
[nodemon] starting `node dist/scripts/dev.js`
/home/dly/rap2-delos/node_modules/_koa-logger@3.2.0@koa-logger/index.js:57
  return async function logger (ctx, next) {
               ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dly/rap2-delos/dist/scripts/app.js:13:16)
[nodemon] app crashed - waiting for file changes before starting...

**复现步骤**
按readme操作，npm run dev之前一切正常。

**期望结果**

**实际结果**
卡在最后一步。

**截图**

截图无法上传。

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
contos7
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by cnxk2009** [comment]
遇到同样错误！！！在线等。。着急。。

**Comment by cnxk2009** [comment]
这个问题怎么解决呢？？？

**Comment by Bosn** [comment]
node.js版本过低。

**Comment by Bosn** [comment]
async await是比较新的JS语法，这个属于JavaScript知识了，可以恶补下async await相关知识。
