### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by zlinux88** [thx/rap2-delos#434]
**BUG描述**
rap2-dolores 目录下执行npm run build 报错
Error: Cannot find module 'async-foreach'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/bin/node-sass:4:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
 

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
求大神 解答

**Comment by zlinux88** [comment]
执行 npm install async-foreach 后继续执行npm run build 依然还是这个错误

**Comment by Bosn** [comment]
node版本是否过老，是否进行了npm install，请仔细看文档，不要缺失任何一步，不要自己创造安装步骤（除非，您很资深）
