### ISSUE TITLE
响应内容导入500异常，附带详细截图，服务器序列化错误

### ISSUE THREAD

**Issue by SummerWindL** [thx/rap2-delos#445]
**BUG描述**

新建接口导入接口使用导入json功能，报错，后台报错！

**复现步骤**

![image](https://user-images.githubusercontent.com/24834548/52838958-65a44880-312f-11e9-9f69-3d486a5bf416.png)

>1.新建接口，点击导入响应内容
>2. 点击确认，响应内容数据填充
>3.点击保存
![image](https://user-images.githubusercontent.com/24834548/52838884-2118ad00-312f-11e9-877f-5eb40d2c3412.png)
>4.后台服务报错 

```
SequelizeDatabaseError: Data truncated for column 'type' at row 1
      at Query.formatError (/home/rap2/rap2-delos/rap2-delos-master/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
      at Query.handler [as onResult] (/home/rap2/rap2-delos/rap2-delos-master/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
      at Query.execute (/home/rap2/rap2-delos/rap2-delos-master/node_modules/mysql2/lib/commands/command.js:30:14)
      at Connection.handlePacket (/home/rap2/rap2-delos/rap2-delos-master/node_modules/mysql2/lib/connection.js:449:32)
      at PacketParser.Connection.packetParser.p [as onPacket] (/home/rap2/rap2-delos/rap2-delos-master/node_modules/mysql2/lib/connection.js:72:12)
      at PacketParser.executeStart (/home/rap2/rap2-delos/rap2-delos-master/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.Connection.stream.on.data (/home/rap2/rap2-delos/rap2-delos-master/node_modules/mysql2/lib/connection.js:79:25)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:601:20)
  From previous event:
      at Query.run (/home/rap2/rap2-delos/rap2-delos-master/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
      at Promise.try.then.connection (/home/rap2/rap2-delos/rap2-delos-master/node_modules/sequelize/lib/sequelize.js:558:20)
  From previous event:
      at Promise.resolve.retryParameters (/home/rap2/rap2-delos/rap2-delos-master/node_modules/sequelize/lib/sequelize.js:555:8)
      at /home/rap2/rap2-delos/rap2-delos-master/node_modules/retry-as-promised/index.js:39:21
      at retryAsPromised (/home/rap2/rap2-delos/rap2-delos-master/node_modules/retry-as-promised/index.js:29:10)
      at Sequelize.query (/home/rap2/rap2-delos/rap2-delos-master/node_modules/sequelize/lib/sequelize.js:454:28)
      at QueryInterface.insert (/home/rap2/rap2-delos/rap2-delos-master/node_modules/sequelize/lib/query-interface.js:901:27)
      at Promise.try.then.then.then (/home/rap2/rap2-delos/rap2-delos-master/node_modules/sequelize/lib/model.js:3685:53)
      at runCallback (timers.js:810:20)
      at tryOnImmediate (timers.js:768:5)
      at processImmediate [as _immediateCallback] (timers.js:745:5)
  From previous event:
      at Property.save (/home/rap2/rap2-delos/rap2-delos-master/node_modules/sequelize/lib/model.js:3661:8)
      at Function.create (/home/rap2/rap2-delos/rap2-delos-master/node_modules/sequelize/lib/model.js:2023:8)
      at Function._target.(anonymous function) [as create] (/home/rap2/rap2-delos/rap2-delos-master/node_modules/sequelize-typescript/lib/models/BaseModel.js:36:41)
      at Object.<anonymous> (/home/rap2/rap2-delos/rap2-delos-master/dist/routes/repository.js:789:47)
      at Generator.next (<anonymous>)
      at fulfilled (/home/rap2/rap2-delos/rap2-delos-master/dist/routes/repository.js:3:58)
      at <anonymous>
```
**期望结果**

能够正常保存

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本

自建服务器
CentOS Linux release 7.6.1810 (Core)

* 如果是前端错误，请提供浏览器版本

* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by SuperTommy007** [comment]
你看看是不是有string类型的值为空了，这个接口保存string类型值不能为空

**Comment by SummerWindL** [comment]
> 你看看是不是有string类型的值为空了，这个接口保存string类型值不能为空

我之前有搭过同样的环境试过同样的json格式导入没有问题，且有string类型为空的情况同样能够保存，这次导入就会报这个错误，我这次给所有的字段赋值也同样存在这个问题，如下
>{
  "resultcode": 1111,
  "resultmsg": "成功",
  "data": {
    "content": [
      {
        "hospcode": "4403050000001",
        "ssid": "8675da161c8e44cbba0e8c22a53e4be9",
        "contractflag": "已签约",
        "idcardno": "422823198110309047",
        "ssphone": "1111",
        "ssname": "01281341",
        "gendercode": "2",
        "gendername": "女",
        "birth": "1981-01-28",
        "age": "38",
        "marriagecode": "1111",
        "marriagename": "--",
        "nationcode": "02",
        "nationname": "蒙古族",
        "disecode": "3",
        "disename": "糖尿病",
        "dxtime": "2019-01-23 14:14:14",
        "dxdeptcode": "003",
        "dxdeptname": "科室3",
        "dxuserid": "admin",
        "dxusername": "admin",
        "diselevel": "2",
        "dxdiseinfo": {
          "disetype": "1",
          "diselevel": "2",
          "diseyears": "1",
          "disetypename": "原发性高血压",
          "diselevelname": "I级高血压(轻度)"
        },
        "sfevaluationresultcode": "1",
        "sfevaluationresultname": "控制未满意",
        "aievaluationresultcode": "1",
        "aievaluationresultname": "控制未满意",
        "maxinspectiontime": "2019-01-29 20:06:44",
        "lastdiabetes": [
          {
            "inspectiontime": "2019-01-29 20:06:44",
            "inspectionitemcode": "1002",
            "inspectionitemname": "生化检验",
            "inspectionsubitemcode": "1001",
            "inspectionsubitemname": "血糖",
            "inspectionindexcode": "1001",
            "inspectionindexname": "空腹血糖",
            "inspectionindexunit": "mmol/L",
            "inspectionindexvalue1": "2",
            "inspectionindexvalue2": "1111",
            "inspectionindexvalue3": "1111",
            "inspectionindexqa": {
              "qacode": "2",
              "qaflag": 2,
              "qaname": "偏低"
            },
            "inspectionindexref": "1111",
            "inspectionindexqaStr": "{qacode:2,qaflag:2,qaname:偏低}"
          },
          {
            "inspectiontime": "2019-01-29 20:06:44",
            "inspectionitemcode": "1002",
            "inspectionitemname": "生化检验",
            "inspectionsubitemcode": "1001",
            "inspectionsubitemname": "血糖",
            "inspectionindexcode": "1001",
            "inspectionindexname": "空腹血糖",
            "inspectionindexunit": "mmol/L",
            "inspectionindexvalue1": "2",
            "inspectionindexvalue2": "1111",
            "inspectionindexvalue3": "1111",
            "inspectionindexqa": {
              "qacode": "2",
              "qaflag": 2,
              "qaname": "偏低"
            },
            "inspectionindexref": "1111",
            "inspectionindexqaStr": "{qacode:2,qaflag:2,qaname:偏低}"
          },
          {
            "inspectiontime": "2019-01-29 20:06:44",
            "inspectionitemcode": "1002",
            "inspectionitemname": "生化检验",
            "inspectionsubitemcode": "1001",
            "inspectionsubitemname": "血糖",
            "inspectionindexcode": "1001",
            "inspectionindexname": "空腹血糖",
            "inspectionindexunit": "mmol/L",
            "inspectionindexvalue1": "2",
            "inspectionindexvalue2": "1111",
            "inspectionindexvalue3": "1111",
            "inspectionindexqa": {
              "qacode": "2",
              "qaflag": 2,
              "qaname": "偏低"
            },
            "inspectionindexref": "1111",
            "inspectionindexqaStr": "{qacode:2,qaflag:2,qaname:偏低}"
          }
        ],
        "gyflag": 1,
        "gyinfo": 1,
        "gytimes": 1,
        "sftimes": 1
      }
    ],
    "last": true,
    "totalElements": 2,
    "totalPages": 1,
    "number": 1,
    "size": 1,
    "sort": "1111",
    "first": true,
    "numberOfElements": 2
  }
}

**Comment by SuperTommy007** [comment]
这些值我这边试了可以保存
![_106](https://user-images.githubusercontent.com/36689187/52924814-4ee93600-3369-11e9-8c03-488113123b30.png)

**Comment by SummerWindL** [comment]
那应该是环境问题了，我这边这种有多级关系格式的都不能保存，具体什么环境问题就不清楚了。没时间去排查

**Comment by SummerWindL** [comment]
我找到问题了，有
![image](https://user-images.githubusercontent.com/24834548/52935194-b61be000-3393-11e9-8a4f-48b7c459f014.png)
这种的他转不了，谢谢了
