### ISSUE TITLE
npm run create-db 报错 

### ISSUE THREAD

**Issue by Shinerain** [thx/rap2-delos#46]
rap2-delos\scripts\init\index.js

async function main () {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

**Comment by Bosn** [comment]
node版本不对，不支持es特性。看下package中最低的Node版本要求。建议安装官方的最新版本。
