### ISSUE TITLE
线上无法编辑

### ISSUE THREAD

**Issue by lazyTai** [thx/rap2-delos#493]
**BUG描述**
https://rap.renqilai.com/repository/editor?id=43&mod=291&itf=1730
这个是我的路径

Uncaught TypeError: t.match is not a function
    at Object.value (main.edc7614e.js:6)
    at Object.diff (main.edc7614e.js:6)
    at Object.properties (main.edc7614e.js:6)
    at Object.diff (main.edc7614e.js:6)
    at Object.items (main.edc7614e.js:6)
    at Object.diff (main.edc7614e.js:6)
    at Object.properties (main.edc7614e.js:6)
    at Object.diff (main.edc7614e.js:6)
    at Object.items (main.edc7614e.js:6)
    at Object.diff (main.edc7614e.js:6)
main.edc7614e.js:30 REPOSITORY_FETCH_SUCCEEDED
main.edc7614e.js:30 Object
main.edc7614e.js:7 uncaught at d TypeError: t.match is not a function
    at Object.value (https://rap.renqilai.com/static/js/main.edc7614e.js:6:18056)
    at Object.diff (https://rap.renqilai.com/static/js/main.edc7614e.js:6:16601)
    at Object.properties (https://rap.renqilai.com/static/js/main.edc7614e.js:6:19198)
    at Object.diff (https://rap.renqilai.com/static/js/main.edc7614e.js:6:16621)
    at Object.items (https://rap.renqilai.com/static/js/main.edc7614e.js:6:20162)
    at Object.diff (https://rap.renqilai.com/static/js/main.edc7614e.js:6:16646)
    at Object.properties (https://rap.renqilai.com/static/js/main.edc7614e.js:6:19198)
    at Object.diff (https://rap.renqilai.com/static/js/main.edc7614e.js:6:16621)
    at Object.items (https://rap.renqilai.com/static/js/main.edc7614e.js:6:20162)
    at Object.diff (https://rap.renqilai.com/static/js/main.edc7614e.js:6:16646)

打开看了一下console的输出  报错了

**复现步骤**
可以和我拿账号密码，登录到我的那个接口看看 为什么无法编辑

**期望结果**

可以和我拿账号密码，登录到我的那个接口看看 为什么无法编辑
**实际结果**
可以和我拿账号密码，登录到我的那个接口看看 为什么无法编辑

**截图**
￼￼
![image](https://user-images.githubusercontent.com/16125707/57745857-5ec2ad00-7701-11e9-9104-f6c6afea71dc.png)

**环境**
* 是前端错误

**附加信息**

**Comment by Bosn** [comment]
点击编辑时，看下发送的lock请求返回的是什么

**Comment by Bosn** [comment]
该issue已过期，若最新部署版本问题依旧，请重新reopen，谢谢。
