### ISSUE TITLE
无法搜索成员

### ISSUE THREAD

**Issue by 1053531172** [thx/rap2-delos#507]
**BUG描述**
创建仓库时无法搜索成员

**复现步骤**
创建仓库，在成员那输入字符就报错

**期望结果**
输入成员名字出现成员列表

**实际结果**
没有任何名字列表，后台接口报错

**截图**
 Error: Invalid value { '$like': '%c%' }
      at Object.escape (/root/rap2-delos/node_modules/sequelize/lib/sql-string.js:65:11)
      at MySQLQueryGenerator.escape (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:966:22)
      at MySQLQueryGenerator._whereParseSingleValueObject (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2433:41)
      at MySQLQueryGenerator.whereItemQuery (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2151:19)
      at Utils.getComplexKeys.forEach.prop (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2050:25)
      at Array.forEach (<anonymous>)
      at MySQLQueryGenerator.whereItemsQuery (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2048:35)
      at value.map.item (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2184:30)
      at Array.map (<anonymous>)
      at MySQLQueryGenerator._whereGroupBind (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2183:21)
      at MySQLQueryGenerator.whereItemQuery (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2119:19)
      at Utils.getComplexKeys.forEach.prop (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2050:25)
      at Array.forEach (<anonymous>)
      at MySQLQueryGenerator.whereItemsQuery (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2048:35)
      at value.map.item (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2184:30)
      at Array.map (<anonymous>)
      at MySQLQueryGenerator._whereGroupBind (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2183:21)
      at MySQLQueryGenerator.whereItemQuery (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2119:19)
      at Utils.getComplexKeys.forEach.prop (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2050:25)
      at Array.forEach (<anonymous>)
      at MySQLQueryGenerator.whereItemsQuery (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2048:35)
      at MySQLQueryGenerator.getWhereConditions (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2460:19)
      at MySQLQueryGenerator.selectQuery (/root/rap2-delos/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1281:28)
      at QueryInterface.rawSelect (/root/rap2-delos/node_modules/sequelize/lib/query-interface.js:1156:37)
      at Function.aggregate (/root/rap2-delos/node_modules/sequelize/lib/model.js:1985:32)
      at Function.Model.(anonymous function) (/root/rap2-delos/node_modules/sequelize-typescript/dist/model/model/model.js:116:28)
      at Function.Model.(anonymous function) [as aggregate] (/root/rap2-delos/node_modules/sequelize-typescript/dist/model/model/model.js:128:28)
      at Promise.try.then (/root/rap2-delos/node_modules/sequelize/lib/model.js:2035:19)
  From previous event:
      at Function.count (/root/rap2-delos/node_modules/sequelize/lib/model.js:2019:8)
      at Function.Model.(anonymous function) [as count] (/root/rap2-delos/node_modules/sequelize-typescript/dist/model/model/model.js:116:28)
      at router_1.default.get (/root/rap2-delos/dist/routes/account.js:44:37)
      at dispatch (/root/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/root/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at /root/rap2-delos/node_modules/koa-router/lib/router.js:346:16
      at dispatch (/root/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at /root/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
      at dispatch (/root/rap2-delos/node_modules/koa-router/lib/router.js:351:31)
      at dispatch (/root/rap2-delos/node_modules/koa-compose/index.js:42:32)
      at /root/rap2-delos/node_modules/koa-body/index.js:141:14

**环境**
自建服务器， CentOS 7.4 64位

**Comment by Bosn** [comment]
fixed in https://github.com/thx/rap2-delos/commit/2502acbf4551be9e7f1aa716a43ffaa38369697f
