### ISSUE TITLE
新建仓库添加成员失败

### ISSUE THREAD

**Issue by 1053531172** [thx/rap2-delos#512]
**BUG描述**
在仓库编辑页面，添加成员，无法成功添加

**复现步骤**

**期望结果**
正常为仓库添加成员

**实际结果**

**截图**
Unhandled rejection SequelizeDatabaseError: Field 'createdAt' doesn't have a default value
    at Query.formatError (/root/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/root/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/root/rap2-delos/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/root/rap2-delos/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/root/rap2-delos/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/root/rap2-delos/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/root/rap2-delos/node_modules/mysql2/lib/connection.js:79:25)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
From previous event:
    at Query.run (/root/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/root/rap2-delos/node_modules/sequelize/lib/sequelize.js:561:20)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
From previous event:
    at Promise.resolve.retryParameters (/root/rap2-delos/node_modules/sequelize/lib/sequelize.js:558:8)
    at /root/rap2-delos/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/root/rap2-delos/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/root/rap2-delos/node_modules/sequelize/lib/sequelize.js:457:28)
    at QueryInterface.bulkInsert (/root/rap2-delos/node_modules/sequelize/lib/query-interface.js:1013:27)
    at Promise.try.then.then (/root/rap2-delos/node_modules/sequelize/lib/model.js:2428:36)
From previous event:
    at Function.bulkCreate (/root/rap2-delos/node_modules/sequelize/lib/model.js:2379:8)
    at Function._target.(anonymous function) [as bulkCreate] (/root/rap2-delos/node_modules/sequelize-typescript/lib/models/BaseModel.js:36:41)
    at association.through.model.findAll.then.currentRows (/root/rap2-delos/node_modules/sequelize/lib/associations/belongs-to-many.js:590:49)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
From previous event:
    at BelongsToMany.set (/root/rap2-delos/node_modules/sequelize/lib/associations/belongs-to-many.js:531:87)
    at Repository.obj.(anonymous function) [as setMembers] (/root/rap2-delos/node_modules/sequelize/lib/associations/helpers.js:69:40)
    at Repository.BaseModel.$set (/root/rap2-delos/node_modules/sequelize-typescript/lib/models/BaseModel.js:120:62)
    at Object.<anonymous> (/root/rap2-delos/dist/routes/repository.js:269:18)
    at Generator.next (<anonymous>)
    at fulfilled (/root/rap2-delos/dist/routes/repository.js:3:58)

**环境**
自建服务器，centos7.4

**附加信息**

**Comment by IrvingZhao** [comment]
`repositories_members`的`createdAt` 有`not null` 约束，可以去掉试试

**Comment by 1053531172** [comment]
还是不行，将not null约束去掉之后，后台没有报错了，但是还是无法添加成功

**Comment by Bosn** [comment]
更新到最新了吗？

**Comment by Bosn** [comment]
昨天有修复成员添加失败的bug。可以看下release 0.0.1，rap2-delos

**Comment by 1053531172** [comment]
已经可以了，谢谢了，反馈很快
