### ISSUE TITLE
注册失败，提示服务端异常

### ISSUE THREAD

**Issue by jin82** [thx/rap2-delos#573]
**BUG描述**
之间环境，docker compose部署 ，注册异常
SequelizeDatabaseError: Can't get stat of './rap2/Users.TRG' (Errcode: 13 - Permission denied)
      at Query.formatError (/app/node_modules/sequelize/lib/dialects/mysql/query.js:228:16)
      at Query.connection.query [as onResult] (/app/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
      at Query.Command.execute (/app/node_modules/mysql2/lib/commands/command.js:30:12)
      at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:515:28)
      at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:94:16)
      at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:77:14)
      at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:102:29)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:607:20)

**复现步骤**
注册

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
自建服务器，
Linux 203 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.6.1810 (Core) 
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64
 Experimental:    false

docker-compose -version
docker-compose version 1.24.1, build 4667896b

**附加信息**

**Comment by jin82** [comment]
使用自己的mysql就没问题了，docker-compose 估计里面配置的mysql有问题

**Comment by Bosn** [comment]
@bigfengyu 看下，最新docker是否已解决
