### ISSUE TITLE
docker 连外部数据库无法链接

### ISSUE THREAD

**Issue by huangzhaorongit** [thx/rap2-delos#602]
**BUG描述**
WARNING: The XZVk3WFpSXaNZPa variable is not set. Defaulting to a blank string.
Unable to connect to the database: ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT
    at /app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:133:19
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21) {
  name: 'SequelizeConnectionError',
  parent: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/app/node_modules/mysql2/lib/connection.js:169:17)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  original: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/app/node_modules/mysql2/lib/connection.js:169:17)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  }
}
(node:101) UnhandledPromiseRejectionWarning: SequelizeConnectionError: connect ETIMEDOUT
    at /app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:133:19
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
(node:101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**复现步骤**

**期望结果**

**实际结果**

**截图**

![image](https://user-images.githubusercontent.com/16186732/68849374-e74ff380-070c-11ea-8cd2-bd91da51f256.png)
*环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
您好，精力有限本issues区域不负责教学。。。
数据库配置和连接问题请自行解决嗷┗|｀O′|┛ 嗷~~ 

如有BUG、意见反馈欢迎提出哦。
