### ISSUE TITLE
接口无法修改

### ISSUE THREAD

**Issue by lovingshu** [thx/rap2-delos#623]
**BUG描述**
之前使用一直正常，但是突然今天任何保存/新建操作都会报异常，清空redis也无效。排除数据库连不上，redis连不上的问题，因为把redis清空后也是可以正常登陆并且获取相关接口信息的，同时也会生成新的缓存数据在redis中.

异常如下:
  xxx POST /interface/create 500 215ms -

  SequelizeUniqueConstraintError: Validation error
      at Query.formatError (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:222:16)
      at Execute.handler [as onResult] (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:50:23)
      at Execute.execute (/home/web/gitprojects/rap2-delos/node_modules/mysql2/lib/commands/command.js:30:14)
      at Connection.handlePacket (/home/web/gitprojects/rap2-delos/node_modules/mysql2/lib/connection.js:449:32)
      at PacketParser.Connection.packetParser.p [as onPacket] (/home/web/gitprojects/rap2-delos/node_modules/mysql2/lib/connection.js:72:12)
      at PacketParser.executeStart (/home/web/gitprojects/rap2-delos/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.Connection.stream.on.data (/home/web/gitprojects/rap2-delos/node_modules/mysql2/lib/connection.js:79:25)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:601:20)
  From previous event:
      at Query.run (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:39:12)
      at runHooks.then.then (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/sequelize.js:641:29)
  From previous event:
      at Promise.try.then.connection (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/sequelize.js:641:12)
  From previous event:
      at Promise.resolve.retry (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/sequelize.js:637:10)
      at /home/web/gitprojects/rap2-delos/node_modules/retry-as-promised/index.js:70:21
      at new Promise (<anonymous>)
      at retryAsPromised (/home/web/gitprojects/rap2-delos/node_modules/retry-as-promised/index.js:60:10)
      at Promise.try (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/sequelize.js:627:30)
  From previous event:
      at Sequelize.query (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/sequelize.js:576:23)
      at QueryInterface.insert (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/query-interface.js:885:27)
      at Promise.try.then.then.then (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/model.js:3824:52)
      at runCallback (timers.js:810:20)
      at tryOnImmediate (timers.js:768:5)
      at processImmediate [as _immediateCallback] (timers.js:745:5)
  From previous event:
      at Logger.save (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/model.js:3801:8)
      at Function.create (/home/web/gitprojects/rap2-delos/node_modules/sequelize/lib/model.js:2222:8)
      at Function.Model.(anonymous function) (/home/web/gitprojects/rap2-delos/node_modules/sequelize-typescript/dist/model/model/model.js:116:28)
      at Function.Model.(anonymous function) [as create] (/home/web/gitprojects/rap2-delos/node_modules/sequelize-typescript/dist/model/model/model.js:128:28)
      at router_1.default.post (/home/web/gitprojects/rap2-delos/dist/routes/repository.js:514:27)
      at dispatch (/home/web/gitprojects/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/home/web/gitprojects/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at router_1.default.post (/home/web/gitprojects/rap2-delos/dist/routes/repository.js:511:12)
      at <anonymous>

**复现步骤**

**期望结果**

**实际结果**
虽然会报错，但是数据会成功保存一半，也就是比如修改接口名称，点击保存时，没反应，然后服务端报出上述异常，刷新后其实又修改成功了,但是对于新建操作只保存成功了接口信息，对于后续的接口初始操作并没有完成，所以导致在选择这个新建的接口时右边不会有对应的接口编辑界面出现

**截图**

**环境**
centOS7,mysql5.7,redis 5

**附加信息**

**Comment by Bosn** [comment]
看起来像是特定的环境问题，可以再自行排查下扔有问题可以reopen。目前没有其它用户报告类似问题。
