### ISSUE TITLE
npm start无法启动

### ISSUE THREAD

**Issue by wyxy2005** [thx/rap2-delos#647]
**BUG描述**
npm run dev 正常运行，可以显示请求日志
但是使用npm start 就报错，无法启动

**复现步骤**

**期望结果**

**实际结果**
npm start

> rap2-delos@2.8.0 start /usr/local/src/rap2/rap2-delos
> cross-env NODE_ENV=production pm2 start dist/dispatch.js --name=rap-server-delos

events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: spawn pm2 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn pm2',
  path: 'pm2',
  spawnargs: [ 'start', 'dist/dispatch.js', '--name=rap-server-delos' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-delos@2.8.0 start: `cross-env NODE_ENV=production pm2 start dist/dispatch.js --name=rap-server-delos`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-delos@2.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
自建 debian8
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息
npm 6.13.4
node v12.16.1

**附加信息**

**Comment by wyxy2005** [comment]
已经解决，原因是npm 全局安装pm2后还需要手动link pm2下，不然找不到pm2命令
