### ISSUE TITLE
mysql5.7 表名大小写异常

### ISSUE THREAD

**Issue by WeekiXu** [thx/rap2-delos#66]
MySQL5.7是大小写敏感，建表语句是小写表名，查询时又用首字母大写，多少有些不便利
数据库同时还跑着其他服务，不方便停库重新配置，还希望能做下规范修改。

`SequelizeDatabaseError: Table 'RAP2_DELOS_APP.Users' doesn't exist
      at Query.formatError (/opt/mock/rap2-delos-master/node_modules/sequelize/lib/dialects/mysql/query.js:228:16)
      at Query.connection.query [as onResult] (/opt/mock/rap2-delos-master/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)`

**Comment by WeekiXu** [comment]
MySQL配置 lower_case_table_names=1 后，无法识别database
`rap2-dolores is running as http://localhost:8088
Unable to connect to the database: { SequelizeConnectionError: Unknown database 'rap2_delos_app'
`

**Comment by WeekiXu** [comment]
自己改mysql配置了；

**Comment by wxungang** [comment]
MySQL配置 lower_case_table_names=1 后，database 也用重新创建小写的rap2_delos_app了。
还是报错：
SequelizeDatabaseError: Table 'rap2_delos_app.users' doesn't exist
      at Query.formatError (/usr/local/mocks/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
      at Query.handler [as onResult] (/usr/local/mocks/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
      at Query.execute (/usr/local/mocks/rap2-delos/node_modules/mysql2/lib/commands/command.js:30:14)
      at Connection.handlePacket (/usr/local/mocks/rap2-delos/node_modules/mysql2/lib/connection.js:449:32)
      at PacketParser.Connection.packetParser.p [as onPacket] (/usr/local/mocks/rap2-delos/node_modules/mysql2/lib/connection.js:72:12)
      at PacketParser.executeStart (/usr/local/mocks/rap2-delos/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.Connection.stream.on.data (/usr/local/mocks/rap2-delos/node_modules/mysql2/lib/connection.js:79:25)
      at Socket.emit (events.js:189:13)
      at addChunk (_stream_readable.js:284:12)
      at readableAddChunk (_stream_readable.js:265:11)
      at Socket.Readable.push (_stream_readable.js:220:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  From previous event:
      at Query.run (/usr/local/mocks/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
      at Promise.try.then.connection (/usr/local/mocks/rap2-delos/node_modules/sequelize/lib/sequelize.js:558:20)
  From previous event:
      at Promise.resolve.retryParameters (/usr/local/mocks/rap2-delos/node_modules/sequelize/lib/sequelize.js:555:8)
      at /usr/local/mocks/rap2-delos/node_modules/retry-as-promised/index.js:39:21
      at retryAsPromised (/usr/local/mocks/rap2-delos/node_modules/retry-as-promised/index.js:29:10)
      at Sequelize.query (/usr/local/mocks/rap2-delos/node_modules/sequelize/lib/sequelize.js:454:28)
      at QueryInterface.rawSelect (/usr/local/mocks/rap2-delos/node_modules/sequelize/lib/query-interface.js:1153:27)
      at Function.aggregate (/usr/local/mocks/rap2-delos/node_modules/sequelize/lib/model.js:1810:32)
      at Function._target.(anonymous function) [as aggregate] (/usr/local/mocks/rap2-delos/node_modules/sequelize-typescript/lib/models/BaseModel.js:36:41)
      at Promise.try.then (/usr/local/mocks/rap2-delos/node_modules/sequelize/lib/model.js:1855:19)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
  From previous event:
      at Function.count (/usr/local/mocks/rap2-delos/node_modules/sequelize/lib/model.js:1839:8)
      at Function._target.(anonymous function) [as count] (/usr/local/mocks/rap2-delos/node_modules/sequelize-typescript/lib/models/BaseModel.js:36:41)
      at Object.<anonymous> (/usr/local/mocks/rap2-delos/dist/routes/account.js:53:37)
      at Generator.next (<anonymous>)
      at /usr/local/mocks/rap2-delos/dist/routes/account.js:6:71
      at new Promise (<anonymous>)
      at __awaiter (/usr/local/mocks/rap2-delos/dist/routes/account.js:2:12)
      at router_1.default.get (/usr/local/mocks/rap2-delos/dist/routes/account.js:42:48)
      at dispatch (/usr/local/mocks/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/usr/local/mocks/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at /usr/local/mocks/rap2-delos/node_modules/koa-router/lib/router.js:346:16
      at dispatch (/usr/local/mocks/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at /usr/local/mocks/rap2-delos/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
      at dispatch (/usr/local/mocks/rap2-delos/node_modules/koa-router/lib/router.js:351:31)
      at dispatch (/usr/local/mocks/rap2-delos/node_modules/koa-compose/index.js:42:32)
      at /usr/local/mocks/rap2-delos/node_modules/koa-body/index.js:141:14
