### ISSUE TITLE
服务无法打开，运行在docker中

### ISSUE THREAD

**Issue by dataSpark-ux** [thx/rap2-delos#675]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
无法打开，服务报错信息，dockcer运行的
TypeError: Cannot set property name of  which has only a getter
      at defaultErrorHanlder (/app/node_modules/koa-generic-session/lib/session.js:558:12)
      at /app/node_modules/koa-generic-session/lib/session.js:193:9
      at Generator.throw (<anonymous>)
      at step (/app/node_modules/koa-generic-session/lib/session.js:3:191)
      at /app/node_modules/koa-generic-session/lib/session.js:3:402
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

**您是否有建议的实现方案**
无

**其它帮助我们理解您需求的描述、截图**
TypeError: Cannot set property name of  which has only a getter
      at defaultErrorHanlder (/app/node_modules/koa-generic-session/lib/session.js:558:12)
      at /app/node_modules/koa-generic-session/lib/session.js:193:9
      at Generator.throw (<anonymous>)
      at step (/app/node_modules/koa-generic-session/lib/session.js:3:191)
      at /app/node_modules/koa-generic-session/lib/session.js:3:402
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by dataSpark-ux** [comment]
已解决，redis的问题
