### ISSUE TITLE
rap2运行一段时间，redis连接超时

### ISSUE THREAD

**Issue by yangb1990** [thx/rap2-delos#695]
[2020-08-06 06:33:35.056] worker#117] Redis connection to 192.168.1.25:6379 failed - read ETIMEDOUT (uncaughtException throw 1 times on pid:117)
[Thu Aug 06 2020 06:33:35 GMT+0000 (Coordinated Universal Time)] [graceful:worker:117:uncaughtException] throw error 1 times
Error: Redis connection to 192.168.1.25:6379 failed - read ETIMEDOUT (uncaughtException throw 1 times on pid:117)
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'read'
}
Error: Redis connection to 192.168.1.25:6379 failed - read ETIMEDOUT (uncaughtException throw 1 times on pid:117)
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[Thu Aug 06 2020 06:33:35 GMT+0000 (Coordinated Universal Time)] [graceful:worker:117] will exit after 10000ms
[Thu Aug 06 2020 06:33:35 GMT+0000 (Coordinated Universal Time)] [graceful:worker:117] close server#0, _connections: 0
[Thu Aug 06 2020 06:33:35 GMT+0000 (Coordinated Universal Time)] [graceful:worker:117] close 1 servers!
[Thu Aug 06 2020 06:33:35 GMT+0000 (Coordinated Universal Time)] [graceful:worker:117] worker disconnect!
[2020-08-06 06:33:35.063] master#1 worker#117 has disconnected.
[Thu Aug 06 2020 06:33:45 GMT+0000 (Coordinated Universal Time)] [graceful:worker:117] kill timeout, exit now.
[2020-08-06 06:33:45.086] master#1 worker#117 died (1). restarting...
Starting task: locker check
[2020-08-06 06:33:46.108]   worker#149 rap2-dolores is running as 38080
[2020-08-06 06:33:46.108] master#1 worker#149 is now connected to null:38080.

**Comment by Bosn** [comment]
运维技术 & 问题超出RAP2本身的讨论范畴，建议在redis运维群或用户交流群中和大家共同交流
