### ISSUE TITLE
启动后执行这个docker-compose exec delos node scripts/init会报错

### ISSUE THREAD

**Issue by duxingxia081** [thx/rap2-delos#726]
启动后执行这个docker-compose exec delos node scripts/init会报错，报错内容如下：
[root@instance-7mun3nj8 rap2-delos]# docker-compose up -d
Creating network "rap2-delos_default" with the default driver
Creating rap2-delos_redis_1   ... done
Creating rap2-delos_dolores_1 ... done
Creating rap2-delos_mysql_1   ... done
Creating rap2-delos_delos_1   ... done
[root@instance-7mun3nj8 rap2-delos]# docker-compose exec delos node scripts/init
Unable to connect to the database: HostNotReachableError [SequelizeHostNotReachableError]: connect EHOSTUNREACH 172.20.0.4:3306
    at /app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:129:19
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21) {
  parent: Error: connect EHOSTUNREACH 172.20.0.4:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
    errno: 'EHOSTUNREACH',
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '172.20.0.4',
    port: 3306,
    fatal: true
  },
  original: Error: connect EHOSTUNREACH 172.20.0.4:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
    errno: 'EHOSTUNREACH',
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '172.20.0.4',
    port: 3306,
    fatal: true
  }
}
(node:32) UnhandledPromiseRejectionWarning: SequelizeHostNotReachableError: connect EHOSTUNREACH 172.20.0.4:3306
    at /app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:129:19
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to redis:6379 failed - connect EHOSTUNREACH 172.20.0.3:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (/app/node_modules/redis/index.js:341:14)
    at Socket.<anonymous> (/app/node_modules/redis/index.js:222:14)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.20.0.3',
  port: 6379
}

**Comment by Bosn** [comment]
docker镜像非官方维护，有问题请在用户群和大家交流谢谢
