### ISSUE TITLE
无法启动生产环境

### ISSUE THREAD

**Issue by qiqizjl** [thx/rap2-delos#73]
已经
~~~ sh
npm install
npm run build
~~~

执行npm start报错
~~~
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:237:13
/data/rap2/api/dist/scripts/worker.js:8
    const server = app.listen(port, () => {
                       ^

TypeError: app.listen is not a function
    at start (/data/rap2/api/dist/scripts/worker.js:8:24)
    at Object.<anonymous> (/data/rap2/api/dist/scripts/worker.js:21:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
[2018-01-19 17:11:14.184] master#5198 worker#5276 has disconnected.
[2018-01-19 17:11:14.185] master#5198 worker#5276 died (1). restarting...
~~~

NodeVersion:9.4.0

SystemVersion:CentOS Linux release 7.4.1708 (Core)

**Comment by Bosn** [comment]
请问npm install成功了嘛？看起来express的package没有正确加载

**Comment by Bosn** [comment]
如有问题请随时reopen
