### ISSUE TITLE
登录接口报 500错 

### ISSUE THREAD

**Issue by ZhengXueNing** [thx/rap2-delos#734]
**BUG描述**
我国庆前还可以正常使用。国庆过来回来后，升级了一下docker。RAP就登录不上了。报500

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/13215544/95531318-d0944880-0a12-11eb-8dad-988481d3bc30.png)
![image](https://user-images.githubusercontent.com/13215544/95531294-c7a37700-0a12-11eb-89ea-c92c59722519.png)
![image](https://user-images.githubusercontent.com/13215544/95531342-d68a2980-0a12-11eb-8c61-d040c8a3148f.png)
![image](https://user-images.githubusercontent.com/13215544/95531358-df7afb00-0a12-11eb-84ad-29925749c8e0.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by ZhengXueNing** [comment]
为了尝试解决上面的问题，我在更新表结构时，发生错误。错误如下:

docker-compose exec delos node scripts/updateSchema
----------------------------------------
DATABASE √
    HOST     mysql
    PORT     3306
    DATABASE rap2
----------------------------------------
升级 DB Schema 中遇到了错误
DatabaseError [SequelizeDatabaseError]: Table 'rap2.users' doesn't exist
    at Query.formatError (/app/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Query.handler [as onResult] (/app/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  parent: Error: Table 'rap2.users' doesn't exist
      at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:425:32)
      at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'rap2.users' doesn't exist",
    sql: 'CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER auto_increment , `fullname` VARCHAR(32) NOT NULL, `password` VARCHAR(32), `email` VARCHAR(128) NOT NULL UNIQUE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB;',
    parameters: undefined
  },
  original: Error: Table 'rap2.users' doesn't exist
      at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:425:32)
      at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'rap2.users' doesn't exist",
    sql: 'CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER auto_increment , `fullname` VARCHAR(32) NOT NULL, `password` VARCHAR(32), `email` VARCHAR(128) NOT NULL UNIQUE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB;',
    parameters: undefined
  },
  sql: 'CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER auto_increment , `fullname` VARCHAR(32) NOT NULL, `password` VARCHAR(32), `email` VARCHAR(128) NOT NULL UNIQUE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB;',
  parameters: undefined
}

**Comment by sany-caobohao** [comment]
可以尝试设置mysql为不区分表名的大小写。mysql中的表应该为Users。

**Comment by ZhengXueNing** [comment]
> 可以尝试设置mysql为不区分表名的大小写。mysql中的表应该为Users。

那您对于我的第一问题，有解决方案吗。登录接口报 500，这让我很崩溃。

**Comment by Bosn** [comment]
运维问题，涉及到环境配置等运维上的常见问题，建议群里交流。
